"""
MINIMAL ORDER -- what a DeltaProduct layer actually has to pay per token.

THE RESULT THAT FORCED THIS FILE
--------------------------------
From the matched-compute sweep at p = 1.0, where EVERY input token is a
5-cycle (transposition length L = 4):

    fixed n_h=1   token 0.0648
    fixed n_h=2   token 0.1207
    fixed n_h=3   token 0.9994   seq 0.9535     <-- solves it
    fixed n_h=4   token 0.9995   seq 0.9600

Three Householder factors track a sequence of 5-cycles. But
exp_beta_reachability.py proved rank(A - I) <= K, and rank(P - I) = L = 4 for a
5-cycle, so three factors cannot represent one. Both results are solid. So one
of the assumptions joining them is wrong, and it is this one:

    "the matrix the layer must apply is the PERMUTATION MATRIX of the token"

It is not. The layer may apply rho(g) for ANY faithful representation rho of the
group it needs to track, and rho is its choice, not ours.

THE HYPOTHESIS
--------------
At p = 1.0 the input alphabet is 24 five-cycles. Five-cycles are even, so they
generate A5, not S5 -- and A5, unlike S5, has a 3-DIMENSIONAL faithful
representation: it is the rotation group of the icosahedron.

In SO(3) every non-identity rotation fixes exactly its axis, so

    rank(R - I) = 2   for every R != I

and by Cartan-Dieudonne every 3-D rotation is a product of exactly TWO
reflections. So in that representation every non-identity element of A5 costs 2
factors, not 4 -- including the 5-cycles. n_h=3 is comfortably enough. (n_h=2
should be enough too, and it failed: representable but not learned. That is a
learnability gap, not a capacity one, and it is worth its own experiment.)

THE PREDICTION THIS MAKES, WHICH IS TESTABLE AND SURPRISING
-----------------------------------------------------------
The cost of a token is not a property of the token. It is a property of the
GROUP GENERATED BY THE WHOLE ALPHABET. So adding a single transposition to an
alphabet of 5-cycles -- the cheapest possible token, L = 1 -- closes the
alphabet over S5 instead of A5, destroys the 3-dimensional representation, and
raises the cost of every 5-cycle from 2 to 4.

Adding an easy token should make the task harder. work/exp_group_closure.py
tests exactly that.

WHAT THIS FILE VERIFIES
-----------------------
  V1  build the icosahedral rotation group from geometry; check |G| = 60 and
      the element-order profile of A5 (1, 15, 20, 24 of orders 1, 2, 3, 5)
  V2  prove it IS A5 by exhibiting the isomorphism: the group permutes the 5
      inscribed octahedra, and that action is faithful and even
  V3  rank(R - I) = 2 for all 59 non-identity elements
  V4  each element factors as exactly 2 Householder reflections, to machine
      precision -- so the cost really is 2, constructively
  V5  the demand table D(g) = min over faithful reps of rank(rho(g) - I),
      against L(g), for S3 / S4 / A4 / A5 / S5

    python work/exp_minimal_order.py
"""

from __future__ import annotations

import itertools
import json
import math
from pathlib import Path

import torch

torch.set_default_dtype(torch.float64)
PHI = (1.0 + math.sqrt(5.0)) / 2.0
TOL = 1e-9


# ---------------------------------------------------------------------------
# permutation helpers
# ---------------------------------------------------------------------------

def n_cycles(p) -> int:
    seen = [False] * len(p)
    c = 0
    for i in range(len(p)):
        if not seen[i]:
            c += 1
            j = i
            while not seen[j]:
                seen[j] = True
                j = p[j]
    return c


def ell(p) -> int:
    return len(p) - n_cycles(p)


def parity(p) -> int:
    return ell(p) % 2


def compose(p, q):
    """(p o q)(i) = p(q(i))."""
    return tuple(p[q[i]] for i in range(len(q)))


def order_of(p) -> int:
    ident = tuple(range(len(p)))
    q, o = p, 1
    while q != ident:
        q, o = compose(q, p), o + 1
    return o


def perm_matrix(p) -> torch.Tensor:
    P = torch.zeros(len(p), len(p))
    for i, pi in enumerate(p):
        P[pi, i] = 1.0
    return P


def mat_rank(M) -> int:
    return int((torch.linalg.svdvals(M) > TOL).sum().item())


# ---------------------------------------------------------------------------
# V1 -- the icosahedral rotation group, from geometry
# ---------------------------------------------------------------------------

def icosahedron_vertices() -> torch.Tensor:
    """12 vertices: all cyclic permutations of (0, +-1, +-PHI)."""
    base = []
    for s1 in (1.0, -1.0):
        for s2 in (1.0, -1.0):
            base.append((0.0, s1 * 1.0, s2 * PHI))
    vs = []
    for (a, b, c) in base:
        vs.append((a, b, c))
        vs.append((c, a, b))
        vs.append((b, c, a))
    V = torch.tensor(sorted(set(vs)))
    assert V.shape == (12, 3), V.shape
    return V


def rotation_group() -> list[torch.Tensor]:
    """Every rotation carrying the icosahedron to itself.

    A rotation is pinned by where one (vertex, neighbouring vertex) flag goes.
    There are 12 * 5 = 60 flags, hence 60 rotations -- built directly rather
    than searched for, so nothing depends on a tolerance.
    """
    V = icosahedron_vertices()
    d2 = torch.cdist(V, V)
    edge = d2[d2 > TOL].min()
    neigh = [[j for j in range(12) if abs(d2[i, j] - edge) < 1e-6]
             for i in range(12)]
    assert all(len(n) == 5 for n in neigh), [len(n) for n in neigh]

    def frame(i, j):
        a = V[i] / V[i].norm()
        w = V[j] - (V[j] @ a) * a
        b = w / w.norm()
        return torch.stack([a, b, torch.linalg.cross(a, b)], dim=1)

    F0 = frame(0, neigh[0][0])
    G = []
    for i in range(12):
        for j in neigh[i]:
            G.append(frame(i, j) @ F0.T)
    return G


def group_key(M: torch.Tensor) -> tuple:
    return tuple(int(round(x * 1e6)) for x in M.flatten().tolist())


def V1() -> dict:
    print("=" * 78)
    print("V1  the icosahedral rotation group")
    print("=" * 78)
    G = rotation_group()
    keys = {group_key(M) for M in G}
    print(f"    elements built            : {len(G)}")
    print(f"    distinct                  : {len(keys)}   "
          f"[{'PASS' if len(keys) == 60 else 'FAIL'}]")

    dets = torch.tensor([torch.linalg.det(M) for M in G])
    orth = max((M @ M.T - torch.eye(3)).abs().max().item() for M in G)
    print(f"    all det = +1 (rotations)  : "
          f"{bool((dets - 1).abs().max() < 1e-9)}")
    print(f"    orthogonality error       : {orth:.2e}")

    closed = True
    for A in G[:12]:
        for B in G:
            if group_key(A @ B) not in keys:
                closed = False
    print(f"    closed under multiplication (sampled) : {closed}   "
          f"[{'PASS' if closed else 'FAIL'}]")

    # element orders
    prof = {}
    for M in G:
        X, o = M.clone(), 1
        while (X - torch.eye(3)).abs().max() > 1e-8 and o < 20:
            X, o = X @ M, o + 1
        prof[o] = prof.get(o, 0) + 1
    want = {1: 1, 2: 15, 3: 20, 5: 24}
    ok = prof == want
    print(f"    element-order profile     : {dict(sorted(prof.items()))}")
    print(f"    matches A5 (1,15,20,24)   : {ok}   [{'PASS' if ok else 'FAIL'}]")
    return {"n": len(keys), "orders": prof, "profile_ok": ok, "closed": closed,
            "G": G}


# ---------------------------------------------------------------------------
# V2 -- the isomorphism to A5, via the 5 inscribed octahedra
# ---------------------------------------------------------------------------

def five_octahedra(V: torch.Tensor):
    """The 15 two-fold axes split into 5 orthogonal triples.

    Edge midpoints give 30 points, 15 antipodal pairs, each a 2-fold axis. Each
    triple of mutually perpendicular axes spans an inscribed octahedron, and
    there are exactly 5 such triples. The rotation group permutes them, and that
    action is the isomorphism onto A5.
    """
    d2 = torch.cdist(V, V)
    edge = d2[d2 > TOL].min()
    mids = []
    for i in range(12):
        for j in range(i + 1, 12):
            if abs(d2[i, j] - edge) < 1e-6:
                m = (V[i] + V[j]) / 2.0
                mids.append(m / m.norm())
    axes = []
    for m in mids:
        if not any((m - a).norm() < 1e-6 or (m + a).norm() < 1e-6 for a in axes):
            axes.append(m)
    assert len(axes) == 15, len(axes)

    triples = []
    for i, j, k in itertools.combinations(range(15), 3):
        a, b, c = axes[i], axes[j], axes[k]
        if (abs(a @ b) < 1e-6 and abs(a @ c) < 1e-6 and abs(b @ c) < 1e-6):
            triples.append(frozenset((i, j, k)))
    assert len(triples) == 5, len(triples)
    return axes, triples


def V2(G) -> dict:
    print()
    print("=" * 78)
    print("V2  the isomorphism onto A5")
    print("=" * 78)
    V = icosahedron_vertices()
    axes, triples = five_octahedra(V)
    print(f"    two-fold axes             : {len(axes)}")
    print(f"    orthogonal triples        : {len(triples)}   "
          f"[{'PASS' if len(triples) == 5 else 'FAIL'}]")

    idx = {t: n for n, t in enumerate(triples)}

    def axis_image(R, i):
        w = R @ axes[i]
        for j, a in enumerate(axes):
            if (w - a).norm() < 1e-6 or (w + a).norm() < 1e-6:
                return j
        raise RuntimeError("axis not preserved")

    perms = []
    for R in G:
        img = {}
        for t in triples:
            s = frozenset(axis_image(R, i) for i in t)
            img[idx[t]] = idx[s]
        perms.append(tuple(img[i] for i in range(5)))

    distinct = len(set(perms))
    all_even = all(parity(p) == 0 for p in perms)
    A5 = [p for p in itertools.permutations(range(5)) if parity(p) == 0]
    onto = set(perms) == set(A5)
    print(f"    action is faithful (60 distinct perms) : {distinct == 60}   "
          f"[{'PASS' if distinct == 60 else 'FAIL'}]")
    print(f"    every image is an EVEN permutation     : {all_even}   "
          f"[{'PASS' if all_even else 'FAIL'}]")
    print(f"    image is exactly A5 (all 60)           : {onto}   "
          f"[{'PASS' if onto else 'FAIL'}]")

    # homomorphism check on a sample
    hom = True
    for a in range(0, 60, 7):
        for b in range(0, 60, 11):
            want = compose(perms[a], perms[b])
            prod = G[a] @ G[b]
            for c in range(60):
                if (G[c] - prod).abs().max() < 1e-8:
                    if perms[c] != want:
                        hom = False
                    break
    print(f"    rho(ab) = rho(a)rho(b) (sampled)       : {hom}   "
          f"[{'PASS' if hom else 'FAIL'}]")
    return {"faithful": distinct == 60, "onto_A5": onto, "hom": hom,
            "perms": perms}


# ---------------------------------------------------------------------------
# V3 / V4 -- rank 2, and an explicit two-reflection factorisation
# ---------------------------------------------------------------------------

def two_reflections(R: torch.Tensor):
    """Write a 3-D rotation as H(2,b) H(2,a), both unit vectors.

    A rotation by theta about axis n is the composition of reflections in two
    planes containing n whose normals are separated by theta/2. Build those
    normals directly from the axis and angle.
    """
    tr = float(torch.clamp((torch.trace(R) - 1.0) / 2.0, -1.0, 1.0))
    theta = math.acos(tr)
    w, Vc = torch.linalg.eig(R)
    axis = None
    for i in range(3):
        if abs(w[i].real - 1.0) < 1e-7 and abs(w[i].imag) < 1e-7:
            axis = Vc[:, i].real
            break
    axis = axis / axis.norm()

    tmp = torch.tensor([1.0, 0.0, 0.0])
    if abs(float(tmp @ axis)) > 0.9:
        tmp = torch.tensor([0.0, 1.0, 0.0])
    a = tmp - (tmp @ axis) * axis
    a = a / a.norm()

    for sign in (1.0, -1.0):
        h = sign * theta / 2.0
        b = (math.cos(h) * a + math.sin(h) * torch.linalg.cross(axis, a))
        b = b / b.norm()
        Ha = torch.eye(3) - 2.0 * torch.outer(a, a)
        Hb = torch.eye(3) - 2.0 * torch.outer(b, b)
        if (Hb @ Ha - R).abs().max() < 1e-8:
            return a, b, (Hb @ Ha - R).norm().item()
    return a, b, (Hb @ Ha - R).norm().item()


def V34(G, perms) -> dict:
    print()
    print("=" * 78)
    print("V3/V4  cost of each element in the 3-dimensional representation")
    print("=" * 78)
    by_order = {}
    worst = 0.0
    bad = 0
    for R, p in zip(G, perms):
        r = mat_rank(R - torch.eye(3))
        L = ell(p)
        o = order_of(p)
        by_order.setdefault((o, L), []).append(r)
        if r != 0:
            _, _, err = two_reflections(R)
            worst = max(worst, err)
            if err > 1e-8:
                bad += 1

    print(f"    {'element type':<28} {'count':>6} {'L (perm rep)':>13} "
          f"{'rank in 3-D':>12}")
    print("    " + "-" * 64)
    names = {(1, 0): "identity", (2, 2): "double transposition",
             (3, 2): "3-cycle", (5, 4): "5-cycle"}
    rows = []
    for (o, L), rs in sorted(by_order.items()):
        rset = sorted(set(rs))
        nm = names.get((o, L), f"order {o}")
        print(f"    {nm:<28} {len(rs):>6} {L:>13} "
              f"{(str(rset[0]) if len(rset) == 1 else str(rset)):>12}")
        rows.append(dict(name=nm, order=o, ell=L, count=len(rs), rank=rset))

    all_two = all(set(rs) == {2} for (o, L), rs in by_order.items() if o > 1)
    print()
    print(f"    every non-identity element has rank 2  : {all_two}   "
          f"[{'PASS' if all_two else 'FAIL'}]")
    print(f"    all factor as exactly 2 reflections    : {bad == 0}   "
          f"[{'PASS' if bad == 0 else 'FAIL'}]   "
          f"worst error {worst:.2e}")
    print()
    print("    So a 5-cycle costs 4 factors inside S5 and 2 inside A5.")
    print("    The token did not change. The alphabet did.")
    return {"rows": rows, "all_rank_two": all_two, "factorisation_ok": bad == 0,
            "worst_err": worst}


# ---------------------------------------------------------------------------
# V5 -- the demand table
# ---------------------------------------------------------------------------

def standard_rep(n):
    """Permutation rep restricted to the sum-zero subspace: the (n-1)-dim
    standard irrep of S_n."""
    B = torch.zeros(n, n - 1)
    for j in range(n - 1):
        v = torch.zeros(n)
        v[: j + 1] = 1.0
        v[j + 1] = -(j + 1.0)
        B[:, j] = v / v.norm()
    return lambda p: B.T @ perm_matrix(p) @ B


def V5(G, perms) -> dict:
    print()
    print("=" * 78)
    print("V5  demand D(g) vs transposition length L(g)")
    print("=" * 78)
    print("    D(g) = min over the faithful reps available to the layer of")
    print("           rank(rho(g) - I).  L(g) is what our oracle currently charges.")
    print()

    out = {}
    for n, name, even_only in ((3, "S3", False), (4, "S4", False),
                               (4, "A4", True), (5, "A5", True),
                               (5, "S5", False)):
        els = [p for p in itertools.permutations(range(n))
               if (not even_only) or parity(p) == 0]
        std = standard_rep(n)
        ranks_std = {}
        for p in els:
            ranks_std[p] = mat_rank(std(p) - torch.eye(n - 1))

        # A5 additionally has the 3-dimensional icosahedral rep
        extra = None
        if name == "A5":
            lookup = {pp: R for pp, R in zip(perms, G)}
            extra = {p: mat_rank(lookup[p] - torch.eye(3)) for p in els}

        buckets = {}
        for p in els:
            L = ell(p)
            d = ranks_std[p] if extra is None else min(ranks_std[p], extra[p])
            buckets.setdefault(L, set()).add(d)

        line = "   ".join(f"L={L}:D={sorted(ds)[0] if len(ds)==1 else sorted(ds)}"
                          for L, ds in sorted(buckets.items()))
        maxD = max(max(ds) for ds in buckets.values())
        maxL = max(buckets)
        flag = "  <-- D < L" if maxD < maxL else ""
        print(f"    {name:<4} |G|={len(els):>3}  min faithful dim "
              f"{3 if name == 'A5' else n-1}   max D = {maxD}  (max L = {maxL})"
              f"{flag}")
        print(f"          {line}")
        # Heterogeneity must be measured over the NON-IDENTITY elements. The
        # identity always costs 0, so including it makes every group look
        # heterogeneous and would have hidden exactly the case that matters.
        nz = {max(ds) for L, ds in buckets.items() if L > 0}
        heterogeneous = len(nz) > 1
        print(f"          demand over non-identity elements: {sorted(nz)}"
              f"   varies: {heterogeneous}"
              f"{'' if heterogeneous else '   <-- adaptivity cannot help here'}")
        out[name] = {"size": len(els), "max_D": maxD, "max_L": maxL,
                     "heterogeneous": heterogeneous,
                     "by_L": {str(k): sorted(v) for k, v in buckets.items()}}
        print()
    return out


# ---------------------------------------------------------------------------

def main():
    print()
    print("#" * 78)
    print("#  MINIMAL ORDER -- the real per-token demand")
    print("#" * 78)
    print()
    v1 = V1()
    G = v1.pop("G")
    v2 = V2(G)
    perms = v2.pop("perms")
    v34 = V34(G, perms)
    v5 = V5(G, perms)

    print("=" * 78)
    print("WHAT THIS CHANGES")
    print("=" * 78)
    print("  1. Our oracle charges L(g). That is correct for S5 -- in the")
    print("     4-dimensional standard rep, rank(rho(g) - I) = L(g) exactly --")
    print("     so the p = 0.05 / 0.1 / 0.25 results stand as measured.")
    print()
    print("  2. It is WRONG for A5. At p = 1.0 the alphabet is 24 five-cycles,")
    print("     which generate A5, where every element costs 2. The oracle")
    print("     charged 4. The 'negative control' fired for the right reason")
    print("     (no gap at p=1) but with the wrong number, and fixed n_h=3")
    print("     solving the task is the tell.")
    print()
    print("  3. The demand is a property of the ALPHABET, not the token. That")
    print("     is the testable prediction: add one transposition to a 5-cycle")
    print("     alphabet -- the cheapest token there is -- and every 5-cycle")
    print("     goes from costing 2 to costing 4.")
    print()
    print("  4. And it bounds our own mechanism honestly: where D is constant")
    print("     across the group (A5), adaptive order cannot help at all. Where")
    print("     D varies (S5), it can. We can now predict which before running.")
    print("=" * 78)

    out = Path("results/minimal_order.json")
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({"V1": v1, "V2": v2, "V34": v34, "V5": v5},
                              indent=2, default=str))
    print(f"\nwritten: {out}\n")


if __name__ == "__main__":
    main()
