"""
GROUP CLOSURE -- does the cost of a token depend on the other tokens?

THE PREDICTION, WRITTEN DOWN BEFORE THE RUN
-------------------------------------------
work/exp_minimal_order.py established (all checks pass, machine precision):

    a 5-cycle costs 4 Householder factors inside S5
    a 5-cycle costs 2 Householder factors inside A5

because A5 has a 3-dimensional faithful representation -- the icosahedral
rotation group -- in which every non-identity element is a rotation, and every
3-D rotation is a product of exactly two reflections. S5 has no 3-dimensional
faithful representation at all, so inside S5 the 4-dimensional standard rep is
the cheapest available and there rank(rho(g) - I) = L(g) = 4.

The token is the same permutation in both cases. What changes is the group the
rest of the alphabet forces the layer to represent.

So the prediction is that adding ONE TRANSPOSITION -- the cheapest token that
exists, L = 1 -- to an alphabet of 5-cycles doubles the cost of every 5-cycle
in the alphabet, because it closes the alphabet over S5 instead of A5.

    n_h = 3  solves an alphabet of 24 five-cycles          (D = 2, fits)
    n_h = 3  FAILS on those same 24 five-cycles plus one transposition
                                                            (D = 4, does not fit)

An easy token making the task harder is not something a per-token difficulty
model can produce. If it happens, per-token difficulty is the wrong model.

THE ARMS
--------
  A5_c5        24 five-cycles                        <A> = A5    D_max = 2
  A5_c5_dt     + 15 double transpositions            <A> = A5    D_max = 2
  A5_c5_3c     + 20 three-cycles                     <A> = A5    D_max = 2
  S5_c5_t1     + exactly ONE transposition           <A> = S5    D_max = 4
  S5_c5_t      + all 10 transpositions               <A> = S5    D_max = 4

A5_c5_3c has 44 distinct tokens, more than S5_c5_t1's 25. So if alphabet SIZE
were driving difficulty, A5_c5_3c would be the harder of the two. The prediction
says the opposite. That is the control.

The confound that cannot be removed: A5 alphabets have 60 reachable targets and
S5 alphabets have 120. It is not the explanation if n_h=4 solves both equally
while n_h=3 splits them -- so the n_h=4 row is doing real work here and is not
padding.

    python work/exp_group_closure.py
    python work/exp_group_closure.py --steps 30000 --arms A5_c5,S5_c5_t1
"""

from __future__ import annotations

import argparse
import itertools
import math
import json
import sys
import time
from pathlib import Path

import torch
import torch.nn.functional as F

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent / "src"))

DEV = "cuda"
DTYPE = torch.bfloat16
N = 5
ELEMENTS = list(itertools.permutations(range(N)))
INDEX = {p: i for i, p in enumerate(ELEMENTS)}
IDENT = tuple(range(N))


# ---------------------------------------------------------------------------
# group
# ---------------------------------------------------------------------------

def compose(p, q):
    return tuple(p[q[i]] for i in range(N))


def n_cycles(p):
    seen = [False] * N
    c = 0
    for i in range(N):
        if not seen[i]:
            c += 1
            j = i
            while not seen[j]:
                seen[j] = True
                j = p[j]
    return c


def ell(p):
    return N - n_cycles(p)


def cycle_type(p):
    seen = [False] * N
    t = []
    for i in range(N):
        if not seen[i]:
            L, j = 0, i
            while not seen[j]:
                seen[j] = True
                j = p[j]
                L += 1
            t.append(L)
    return tuple(sorted(t, reverse=True))


def closure(gens):
    """The subgroup generated by gens."""
    seen = {IDENT}
    frontier = [IDENT]
    while frontier:
        nxt = []
        for a in frontier:
            for g in gens:
                b = compose(a, g)
                if b not in seen:
                    seen.add(b)
                    nxt.append(b)
        frontier = nxt
    return seen


FIVE_CYCLES = [p for p in ELEMENTS if cycle_type(p) == (5,)]
THREE_CYCLES = [p for p in ELEMENTS if cycle_type(p) == (3, 1, 1)]
DOUBLE_TRANS = [p for p in ELEMENTS if cycle_type(p) == (2, 2, 1)]
TRANSPOSITIONS = [p for p in ELEMENTS if cycle_type(p) == (2, 1, 1, 1)]

ALPHABETS = {
    "A5_c5":    FIVE_CYCLES,
    "A5_c5_dt": FIVE_CYCLES + DOUBLE_TRANS,
    "A5_c5_3c": FIVE_CYCLES + THREE_CYCLES,
    "S5_c5_t1": FIVE_CYCLES + TRANSPOSITIONS[:1],
    "S5_c5_t":  FIVE_CYCLES + TRANSPOSITIONS,
}


def predicted_demand(group_size: int) -> int:
    """D_max from exp_minimal_order.py: 2 inside A5, 4 inside S5."""
    return 2 if group_size == 60 else (4 if group_size == 120 else -1)


# ---------------------------------------------------------------------------
# data
# ---------------------------------------------------------------------------

def make_data(alphabet, k, n_seq, seed):
    """Uniform token sequences and their running products, as token ids.

    Token id == index into ELEMENTS, so the vocabulary is shared across arms
    and every arm trains the same sized embedding table.
    """
    g = torch.Generator().manual_seed(seed)
    idx = torch.randint(0, len(alphabet), (n_seq, k), generator=g)
    inp = torch.empty(n_seq, k, dtype=torch.long)
    tgt = torch.empty(n_seq, k, dtype=torch.long)
    for b in range(n_seq):
        acc = IDENT
        row = idx[b].tolist()
        for t, j in enumerate(row):
            x = alphabet[j]
            acc = compose(acc, x)
            inp[b, t] = INDEX[x]
            tgt[b, t] = INDEX[acc]
    return inp, tgt


# ---------------------------------------------------------------------------

@torch.no_grad()
def quick_eval(model, te_x, te_y, limit=512):
    """Token/sequence accuracy on a slice of the test set."""
    model.eval()
    tc = tt = sc = n = 0
    for i in range(0, min(limit, te_x.shape[0]), 128):
        y = te_y[i:i + 128]
        pred = model(input_ids=te_x[i:i + 128]).logits.float().argmax(-1)
        eq = pred == y
        tc += eq.sum().item()
        tt += eq.numel()
        sc += eq.all(-1).sum().item()
        n += y.shape[0]
    model.train()
    return tc / tt, sc / max(1, n)


def run_arm(name, alphabet, n_h, data, args, build):
    tr_x, tr_y, te_x, te_y = data
    model = build(n_h, False, args.n_heads, args.head_dim, args.hidden,
                  args.n_layers, args.vocab, args.seed)
    opt = torch.optim.AdamW(model.parameters(), lr=args.lr)

    # A constant lr of 1e-3 left S5_c5_t1 n_h=4 oscillating between loss 1.83
    # and 2.19 for 80 000 steps with no trend -- the signature of a step size
    # too large to settle, not of a model that lacks capacity. Warmup + cosine
    # is the cheapest thing that distinguishes those two.
    sched = None
    if args.cosine or args.warmup:
        def lr_at(step):
            if step < args.warmup:
                return (step + 1) / max(1, args.warmup)
            if not args.cosine:
                return 1.0
            prog = (step - args.warmup) / max(1, args.steps - args.warmup)
            return 0.5 * (1.0 + math.cos(math.pi * min(1.0, prog)))
        sched = torch.optim.lr_scheduler.LambdaLR(opt, lr_at)

    g = torch.Generator(device=DEV).manual_seed(args.seed)
    t0 = time.perf_counter()
    for step in range(1, args.steps + 1):
        i = torch.randint(0, tr_x.shape[0], (args.batch,), device=DEV, generator=g)
        loss = F.cross_entropy(
            model(input_ids=tr_x[i]).logits.float().flatten(0, 1),
            tr_y[i].flatten())
        opt.zero_grad(set_to_none=True)
        loss.backward()
        opt.step()
        if sched is not None:
            sched.step()
        if step % args.log_every == 0 or step == 1:
            cur = opt.param_groups[0]["lr"]
            msg = (f"      n_h={n_h}  step {step:>7}  loss {loss.item():.4f}"
                   f"  lr {cur:.2e}")
            # A multi-hour cell that reports one number at the end cannot tell
            # you whether it plateaued at step 30k or was still climbing at
            # 200k. That distinction is the entire question here.
            if args.eval_every and step % args.eval_every == 0:
                tok, seq = quick_eval(model, te_x, te_y)
                el = time.perf_counter() - t0
                eta = el / step * (args.steps - step)
                msg += (f"   token {tok:.4f}  seq {seq:.4f}"
                        f"   [{el/3600:.1f}h elapsed, {eta/3600:.1f}h left]")
            print(msg, flush=True)
    dt = time.perf_counter() - t0

    model.eval()
    tc = tt = sc = 0
    with torch.no_grad():
        for i in range(0, te_x.shape[0], 128):
            pred = model(input_ids=te_x[i:i + 128]).logits.float().argmax(-1)
            eq = pred == te_y[i:i + 128]
            tc += eq.sum().item()
            tt += eq.numel()
            sc += eq.all(-1).sum().item()
    del model
    torch.cuda.empty_cache()
    return dict(arm=name, n_h=n_h, token_acc=tc / tt,
                seq_acc=sc / te_x.shape[0], train_s=dt)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--k", type=int, default=128)
    ap.add_argument("--n_train", type=int, default=100000)
    ap.add_argument("--n_test", type=int, default=2000)
    ap.add_argument("--steps", type=int, default=20000)
    ap.add_argument("--batch", type=int, default=128)
    ap.add_argument("--lr", type=float, default=1e-3)
    ap.add_argument("--n_heads", type=int, default=12)
    ap.add_argument("--head_dim", type=int, default=32)
    ap.add_argument("--hidden", type=int, default=128)
    ap.add_argument("--n_layers", type=int, default=1)
    ap.add_argument("--seed", type=int, default=666)
    ap.add_argument("--log_every", type=int, default=5000)
    ap.add_argument("--eval_every", type=int, default=0,
                    help="evaluate mid-training every N steps (0=off)")
    ap.add_argument("--warmup", type=int, default=0,
                    help="linear lr warmup steps")
    ap.add_argument("--cosine", action="store_true",
                    help="cosine-decay the lr to zero over --steps")
    ap.add_argument("--orders", default="2,3,4")
    ap.add_argument("--arms", default="A5_c5,A5_c5_dt,A5_c5_3c,S5_c5_t1,S5_c5_t")
    ap.add_argument("--out", default="results/group_closure.json")
    args = ap.parse_args()

    from exp_matched_compute import build, N_GROUP, N_SPECIAL
    args.vocab = N_GROUP + N_SPECIAL
    if not torch.cuda.is_available():
        raise SystemExit("needs CUDA")

    orders = [int(o) for o in args.orders.split(",")]
    arms = [a.strip() for a in args.arms.split(",")]

    print("=" * 78)
    print("GROUP CLOSURE -- is per-token cost a property of the token?")
    print("=" * 78)
    print(f"  {'arm':<11} {'tokens':>7} {'<A>':>6} {'group':>6} "
          f"{'D_max':>6} {'targets':>8}   prediction")
    print("  " + "-" * 74)
    meta = {}
    for name in arms:
        alpha = ALPHABETS[name]
        grp = closure(alpha)
        D = predicted_demand(len(grp))
        gname = {60: "A5", 120: "S5"}.get(len(grp), f"|G|={len(grp)}")
        meta[name] = dict(n_tokens=len(alpha), group=gname, group_size=len(grp),
                          D_max=D)
        pred = "  ".join(f"n_h={o}:{'solve' if o >= D else 'FAIL'}"
                         for o in orders)
        print(f"  {name:<11} {len(alpha):>7} {gname:>6} {len(grp):>6} "
              f"{D:>6} {len(grp):>8}   {pred}")
    print()
    print("  Note A5_c5_3c has MORE tokens than S5_c5_t1 but is predicted")
    print("  easier. If alphabet size drove difficulty it would be the reverse.")
    print()

    rows = []
    for name in arms:
        alpha = ALPHABETS[name]
        print("-" * 78)
        print(f"ARM {name}   {len(alpha)} tokens, generates {meta[name]['group']}, "
              f"D_max = {meta[name]['D_max']}")
        print("-" * 78)
        inp, tgt = make_data(alpha, args.k, args.n_train + args.n_test, args.seed)
        data = (inp[:args.n_train].to(DEV), tgt[:args.n_train].to(DEV),
                inp[args.n_train:].to(DEV), tgt[args.n_train:].to(DEV))
        for o in orders:
            r = run_arm(name, alpha, o, data, args, build)
            r.update(meta[name])
            rows.append(r)
            print(f"    -> n_h={o}   token {r['token_acc']:.4f}   "
                  f"seq {r['seq_acc']:.4f}   ({r['train_s']:.0f}s)")
            # Written after EVERY cell, not at the end. This run takes hours and
            # is routinely interrupted; losing finished cells to a Ctrl-C is a
            # self-inflicted wound.
            part = Path(args.out).with_suffix(".partial.json")
            part.parent.mkdir(parents=True, exist_ok=True)
            part.write_text(json.dumps({"config": vars(args), "meta": meta,
                                        "results": rows, "complete": False},
                                       indent=2, default=str))
        del data
        torch.cuda.empty_cache()
        print()

    SOLVED = 0.99
    print("=" * 78)
    print(f"{'arm':<11} {'group':>6} {'D_max':>6} " +
          "".join(f"{'n_h=' + str(o):>12}" for o in orders))
    print("-" * 78)
    for name in arms:
        cells = []
        for o in orders:
            r = next(x for x in rows if x["arm"] == name and x["n_h"] == o)
            cells.append(f"{r['token_acc']:>10.4f} "
                         f"{'.' if r['token_acc'] >= SOLVED else 'x'}")
        print(f"{name:<11} {meta[name]['group']:>6} {meta[name]['D_max']:>6} " +
              "".join(f"{c:>12}" for c in cells))

    print("=" * 78)
    # The capacity bound is a LOWER bound: n_h >= D is necessary, not
    # sufficient. So the four outcomes are not symmetric and only one of them
    # can falsify the demand model. Scoring them as plain hit/miss -- which an
    # earlier version of this script did -- counts optimisation failures as
    # evidence against the theory, which they are not.
    consistent = learnability = refuting = 0
    for r in rows:
        enough = r["n_h"] >= r["D_max"]
        solved = r["token_acc"] >= SOLVED
        if enough and solved:
            consistent += 1
        elif not enough and not solved:
            consistent += 1
        elif enough and not solved:
            learnability += 1
            print(f"  LEARNABILITY GAP  {r['arm']} n_h={r['n_h']}: capacity "
                  f"sufficient (D={r['D_max']}) but did not train "
                  f"(token {r['token_acc']:.4f})")
        else:
            refuting += 1
            print(f"  *** REFUTES THE DEMAND MODEL ***  {r['arm']} "
                  f"n_h={r['n_h']} < D={r['D_max']} yet solved it "
                  f"(token {r['token_acc']:.4f})")
    print()
    print(f"  consistent with the bound        : {consistent}")
    print(f"  capacity enough but not learned  : {learnability}   "
          f"(Claim 3 evidence, NOT evidence against Claim 2)")
    print(f"  solved below the bound           : {refuting}   "
          f"{'<-- the model is wrong' if refuting else '(none: model survives)'}")
    print()
    print("  Caution: a plateau failure and a capacity failure are")
    print("  indistinguishable from the outside. A predicted-fail cell that")
    print("  fails is therefore WEAK evidence on its own. The strong evidence")
    print("  is the paired contrast below, on alphabets one token apart.")
    print()

    try:
        a = next(x for x in rows if x["arm"] == "A5_c5" and x["n_h"] == 3)
        b = next(x for x in rows if x["arm"] == "S5_c5_t1" and x["n_h"] == 3)
        print("  THE HEADLINE COMPARISON (n_h = 3, one token apart):")
        print(f"    24 five-cycles                    token {a['token_acc']:.4f}")
        print(f"    the same 24 + ONE transposition   token {b['token_acc']:.4f}")
        d = a["token_acc"] - b["token_acc"]
        if d > 0.3:
            print(f"    adding the cheapest possible token cost "
                  f"{d*100:.1f} accuracy points.")
            print("    Per-token difficulty cannot explain this. The demand is")
            print("    a property of the alphabet's group closure.")
        elif d < 0.05:
            print("    No collapse. The group-closure account is NOT supported;")
            print("    n_h=3 handles S5 five-cycles too, so something outside")
            print("    exact representation is carrying the task.")
        else:
            print(f"    partial effect ({d*100:.1f} points) -- needs more steps "
                  f"or seeds before it means anything.")
    except StopIteration:
        pass
    print("=" * 78)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({"config": vars(args), "meta": meta,
                               "results": rows}, indent=2, default=str))
    print(f"written: {out}")


def _tests() -> bool:
    print("=" * 70)
    print("SELF-TEST")
    print("=" * 70)
    ok = True
    t1 = (len(FIVE_CYCLES), len(THREE_CYCLES), len(DOUBLE_TRANS),
          len(TRANSPOSITIONS)) == (24, 20, 15, 10)
    print(f"  class sizes 24/20/15/10                : {t1}  "
          f"[{'PASS' if t1 else 'FAIL'}]")
    ok &= t1

    for name, want in (("A5_c5", 60), ("A5_c5_dt", 60), ("A5_c5_3c", 60),
                       ("S5_c5_t1", 120), ("S5_c5_t", 120)):
        got = len(closure(ALPHABETS[name]))
        good = got == want
        print(f"  <{name:<9}> = {got:>3}  (want {want:>3})        : {good}  "
              f"[{'PASS' if good else 'FAIL'}]")
        ok &= good

    t3 = len(ALPHABETS["A5_c5_3c"]) > len(ALPHABETS["S5_c5_t1"])
    print(f"  A5_c5_3c has more tokens than S5_c5_t1 : {t3}  "
          f"[{'PASS' if t3 else 'FAIL'}]  "
          f"({len(ALPHABETS['A5_c5_3c'])} vs {len(ALPHABETS['S5_c5_t1'])})")
    ok &= t3

    # one transposition really is the whole difference
    a, b = set(ALPHABETS["A5_c5"]), set(ALPHABETS["S5_c5_t1"])
    t4 = len(b - a) == 1 and ell(list(b - a)[0]) == 1
    print(f"  S5_c5_t1 = A5_c5 + one L=1 token       : {t4}  "
          f"[{'PASS' if t4 else 'FAIL'}]")
    ok &= t4

    inp, tgt = make_data(ALPHABETS["A5_c5"], 16, 64, 0)
    acc_ok = True
    for b_ in range(64):
        acc = IDENT
        for t in range(16):
            acc = compose(acc, ELEMENTS[inp[b_, t].item()])
            if INDEX[acc] != tgt[b_, t].item():
                acc_ok = False
    print(f"  running products correct               : {acc_ok}  "
          f"[{'PASS' if acc_ok else 'FAIL'}]")
    ok &= acc_ok

    tg = {tgt[i, j].item() for i in range(64) for j in range(16)}
    t6 = all(ell(ELEMENTS[i]) % 2 == 0 for i in tg)
    print(f"  A5 alphabet reaches only even perms    : {t6}  "
          f"[{'PASS' if t6 else 'FAIL'}]  ({len(tg)} distinct targets)")
    ok &= t6

    print("=" * 70)
    print("ALL TESTS PASSED" if ok else "TESTS FAILED")
    return ok


if __name__ == "__main__":
    if "--selftest" in sys.argv:
        raise SystemExit(0 if _tests() else 1)
    main()
